name: .NET Core

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.X
    - name: Restore with dotnet
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release
